services:
  - type: web
    name: certificate-project
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CSV_PATH
        value: students.csv
      - key: CERTIFICATES_DIR
        value: certificates
      - key: CERTIFICATE_TEMPLATE_IMAGE
        value: templates/certificate_template.jpg
      - key: CERTIFICATE_ID_PREFIX
        value: CERT
